const METADATA = {
  "1": { "domain": "Configuration", "explanation": "Las Technical Service Offerings sincronizan grupos operativos como Support y Managed By con los CIs asociados mediante Dynamic CI Groups, asegurando consistencia operativa." },
  "2": { "domain": "Ingest", "explanation": "Cada tipo de service mapping se usa según complejidad: top‑down para precisión, connection suggestion para entornos dinámicos y Dynamic CI Groups para agrupaciones simples." },
  "3": { "domain": "Configuration", "explanation": "Crear clases CMDB requiere permisos de modelo y diccionario. sn_cmdb_admin controla estructura y personalize_dictionary permite definir atributos necesarios." },
  "4": { "domain": "Configuration", "explanation": "La relación correcta es 'Runs on', indicando que la aplicación se ejecuta sobre un servidor, siguiendo el modelo estándar de dependencias." },
  "5": { "domain": "Ingest", "explanation": "Asset‑CI Field Mapping permite sincronizar automáticamente campos entre activo y CI, evitando soluciones manuales y manteniendo consistencia." },
  "6": { "domain": "Configuration", "explanation": "La mejor práctica es extender clases existentes y verificar modelos disponibles para evitar duplicados y deuda técnica." },
  "7": { "domain": "Configuration", "explanation": "El Assignment Group se rellena automáticamente desde el CI, permitiendo asignación eficiente en procesos ITSM." },
  "8": { "domain": "Configuration", "explanation": "La relación es muchos-a-muchos porque múltiples aplicaciones pueden ejecutarse en diversos servidores." },
  "9": { "domain": "Configuration", "explanation": "La pestaña 'Added' muestra atributos creados específicamente para la clase, no heredados." },
  "10": { "domain": "Ingest", "explanation": "La sincronización Asset‑CI se logra mediante reglas o lógica automática que mantiene coherencia entre ambos registros." },

  "11": { "domain": "Configuration", "explanation": "El Assignment Group se deriva automáticamente del CI seleccionado, facilitando el routing de incidentes." },
  "12": { "domain": "Configuration", "explanation": "Extender clases o usar modelos del store alinea con mejores prácticas y evita deuda técnica." },
  "13": { "domain": "Govern", "explanation": "Principal Classes se configuran en CI Class Manager para controlar visibilidad en referencias ITSM." },
  "14": { "domain": "Configuration", "explanation": "La regla 'largest value' selecciona el valor más alto entre fuentes disponibles." },
  "15": { "domain": "Ingest", "explanation": "IntegrationHub ETL asegura que los datos pasen por el IRE, garantizando calidad y evitando duplicados." },
  "16": { "domain": "Configuration", "explanation": "Las reglas de reconciliación definen qué fuente de datos es la autoridad en caso de conflicto." },
  "17": { "domain": "Configuration", "explanation": "Dynamic rules permiten seleccionar atributos basados en criterios como 'last updated' o 'most reported'." },
  "18": { "domain": "Configuration", "explanation": "El IRE evalúa reglas en orden de prioridad para decidir si actualizar o insertar registros." },
  "19": { "domain": "Configuration", "explanation": "Reclasificar a una clase más específica corresponde a un Class Upgrade." },
  "20": { "domain": "Configuration", "explanation": "IRE funciona sin CMDB 360; éste solo añade capacidades analíticas adicionales." },

  "21": { "domain": "Ingest", "explanation": "Discovery identifica automáticamente relaciones entre CIs durante el proceso de escaneo." },
  "22": { "domain": "Configuration", "explanation": "Cambiar atributos identificadores puede provocar creación de un nuevo CI en lugar de actualizar el existente." },
  "23": { "domain": "Ingest", "explanation": "ACC se usa para dispositivos no siempre conectados o entornos donde Discovery no es viable." },
  "24": { "domain": "Ingest", "explanation": "Los atributos no descubribles deben mantenerse mediante importaciones externas programadas." },
  "25": { "domain": "Ingest", "explanation": "Cada herramienta CMDB cumple un rol: CI Class Manager estructura, IRE calidad, Data Manager lifecycle y Service Mapping dependencias." },
  "26": { "domain": "Ingest", "explanation": "El script onBefore fuerza el uso del IRE antes de insertar datos." },
  "27": { "domain": "Configuration", "explanation": "Las prioridades de reconciliación determinan qué fuente puede actualizar registros existentes." },
  "28": { "domain": "Ingest", "explanation": "Las customizaciones generan skipped changes para evitar sobrescribir personalizaciones en upgrades." },
  "29": { "domain": "Govern", "explanation": "Correctness mide calidad incluyendo duplicados, staleness y orphan records." },
  "30": { "domain": "Govern", "explanation": "Completeness, Correctness y Compliance representan dimensiones clave de calidad CMDB." },

  "31": { "domain": "Govern", "explanation": "El dashboard de deduplicación permite gestionar duplicados centralizadamente en CMDB Workspace." },
  "32": { "domain": "Govern", "explanation": "Se conserva el CI descubierto y se fusionan relaciones críticas del manual para mantener precisión y contexto." },
  "33": { "domain": "Govern", "explanation": "Archive policies automatizan limpieza de registros antiguos o inactivos." },
  "34": { "domain": "Govern", "explanation": "Las políticas de certificación validan cumplimiento, como revisión de parches." },
  "35": { "domain": "Govern", "explanation": "Correctness incluye Duplicate, Orphan y Stale CIs." },
  "36": { "domain": "Govern", "explanation": "Attestation valida existencia; Certification valida datos." },
  "37": { "domain": "Govern", "explanation": "Los playbooks del Health Dashboard proporcionan guías de resolución estructurada." },
  "38": { "domain": "Govern", "explanation": "El dashboard mide calidad con métricas como Stale y Duplicate CIs." },
  "39": { "domain": "Govern", "explanation": "Health Inclusion Rules limitan el alcance de CIs evaluados por métrica." },
  "40": { "domain": "Govern", "explanation": "Data Manager genera tareas automáticas visibles en CMDB Workspace." },

  "41": { "domain": "Govern", "explanation": "Archive policies mantienen el volumen de CMDB controlado eliminando datos antiguos." },
  "42": { "domain": "Govern", "explanation": "Los scheduled jobs son necesarios para calcular métricas del Health Dashboard." },
  "43": { "domain": "Govern", "explanation": "Managed By Group define responsabilidad operativa y se usa en tareas." },
  "44": { "domain": "Govern", "explanation": "Las tareas se centralizan en 'Important actions' dentro de CMDB Workspace." },
  "45": { "domain": "Govern", "explanation": "Certification crea tareas para validar datos de CIs." },
  "46": { "domain": "Govern", "explanation": "Cada rol tiene funciones claras en gestión del CMDB." },
  "47": { "domain": "Govern", "explanation": "Las reglas previenen duplicados y herramientas permiten su remediación." },
  "48": { "domain": "Govern", "explanation": "Attestation valida que los CIs existen realmente." },
  "49": { "domain": "Govern", "explanation": "Data Manager automatiza archivado y eliminación de registros." },
  "50": { "domain": "Govern", "explanation": "Las políticas se gestionan en CMDB Workspace." },

  "51": { "domain": "Insight", "explanation": "Los productos ServiceNow mejoran Incident Management mediante automatización y visibilidad." },
  "52": { "domain": "Insight", "explanation": "Las Saved Queries se gestionan en CMDB 360 dentro del Workspace." },
  "53": { "domain": "Insight", "explanation": "Service Mapping permite evaluar impacto de cambios en servicios." },
  "54": { "domain": "Insight", "explanation": "NLQ permite consultar CMDB usando lenguaje natural." },
  "55": { "domain": "Insight", "explanation": "Service Offerings ayudan a identificar usuarios afectados." },
  "56": { "domain": "Insight", "explanation": "Unified Map visualiza relaciones entre CIs." },
  "57": { "domain": "Insight", "explanation": "El panel de filtros reduce ruido visual en el mapa." },
  "58": { "domain": "Insight", "explanation": "La query combina tablas y filtros para obtener datos relevantes." },
  "59": { "domain": "CSDM", "explanation": "Los Information Objects representan datos críticos de negocio." },
  "60": { "domain": "CSDM", "explanation": "Los sistemas técnicos pertenecen al dominio Service Delivery." },

  "61": { "domain": "CSDM", "explanation": "Los Information Objects almacenan datos regulatorios asociados a aplicaciones." },
  "62": { "domain": "CSDM", "explanation": "La fase Walk mejora organización operativa y soporte técnico." },
  "63": { "domain": "CSDM", "explanation": "Lifecycle objects organizan estados de CIs estructuradamente." },
  "64": { "domain": "Govern", "explanation": "El Data Foundation Dashboard identifica gaps de calidad." },
  "65": { "domain": "CSDM", "explanation": "Technology Service Owners definen requerimientos de servicio." },
  "66": { "domain": "Insight", "explanation": "Los dashboards permiten monitorizar actividad de CIs." },
  "67": { "domain": "Insight", "explanation": "El Data Foundations Dashboard ofrece insights accionables." },
  "68": { "domain": "CSDM", "explanation": "CSDM ayuda a evaluar impacto y routing de cambios." },
  "69": { "domain": "Insight", "explanation": "El CMDB mejora resiliencia y operaciones ITSM." },
  "70": { "domain": "Govern", "explanation": "Los playbooks ayudan a mejorar calidad del modelo." },

  "71": { "domain": "Govern", "explanation": "Los pasos clave son analizar y corregir datos." },
  "72": { "domain": "Govern", "explanation": "Life Cycle Mapping conecta estados legacy y nuevos." },
  "73": { "domain": "Govern", "explanation": "Se deben validar datos antes de eliminar duplicados." },
  "74": { "domain": "CSDM", "explanation": "Los objetos se asignan a dominios CSDM." },
  "75": { "domain": "CSDM", "explanation": "El rollout sigue Foundation → Crawl → Walk → Run → Fly." },
  "76": { "domain": "Configuration", "explanation": "Las reglas de identificación se gestionan en CI Class Manager." },
  "77": { "domain": "Govern", "explanation": "Principal Class mejora usabilidad en formularios." },
  "78": { "domain": "Configuration", "explanation": "Se habilita multisource mediante propiedad del sistema." },
  "79": { "domain": "Configuration", "explanation": "CI Class Manager es la fuente central de configuración." },
  "80": { "domain": "Configuration", "explanation": "Health Inclusion limita alcance de identificación." },

  "81": { "domain": "Insight", "explanation": "Saved y encoded queries permiten agrupar CIs." },
  "82": { "domain": "Configuration", "explanation": "Los valores de Service Offering sobrescriben CI Class Manager." },
  "83": { "domain": "Configuration", "explanation": "Change y Support Group se sincronizan automáticamente." },
  "84": { "domain": "Configuration", "explanation": "Crear clases heredando asegura integración CMDB." },
  "85": { "domain": "Govern", "explanation": "Principal Class se configura en Basic Info." },
  "86": { "domain": "Govern", "explanation": "Se deben corregir discrepancias tras lifecycle sync." },
  "87": { "domain": "Configuration", "explanation": "Principal Class se configura en pestaña Basic Info." },
  "88": { "domain": "Configuration", "explanation": "El prefijo u_ indica tablas personalizadas." },
  "89": { "domain": "Configuration", "explanation": "Las reglas de identificación se configuran para evitar duplicados." },
  "90": { "domain": "Ingest", "explanation": "Service Offerings permiten poblar Support Group automáticamente." },

  "91": { "domain": "Configuration", "explanation": "Fallback permite usar reglas de clase padre si necesario." },
  "92": { "domain": "Configuration", "explanation": "El icono se define en Basic Info." },
  "93": { "domain": "Govern", "explanation": "Life Cycle Mapping muestra transición de estados." },
  "94": { "domain": "Configuration", "explanation": "Se requieren roles de CMDB y diccionario para modificar clases." },
  "95": { "domain": "Insight", "explanation": "Dynamic CI Groups expanden CIs en cambios." },
  "96": { "domain": "Configuration", "explanation": "Principal Class se activa mediante checkbox." },
  "97": { "domain": "Configuration", "explanation": "Las reglas IRE junto con CI Class Manager aseguran estandarización y evitan duplicados consolidando datos multisource correctamente." },
  "98": { "domain": "Govern", "explanation": "Pinned Classes mejoran la eficiencia del CI Class Owner al permitir acceso rápido a clases gestionadas frecuentemente." },
  "99": { "domain": "Insight", "explanation": "Dynamic CI Groups permiten aplicar cambios a múltiples CIs agrupados dinámicamente mediante filtros." },
  "100": { "domain": "Configuration", "explanation": "El atributo Configuration File Path diferencia múltiples instancias de software en un mismo servidor evitando duplicados." },

  "101": { "domain": "Configuration", "explanation": "Mover un CI a una subclase más específica es un Class Upgrade dentro de la jerarquía CMDB." },
  "102": { "domain": "Ingest", "explanation": "Los productos ServiceNow se asignan a funciones según su rol en ingestión o gestión de datos." },
  "103": { "domain": "Configuration", "explanation": "Las Data Refresh Rules permiten actualizar datos cuando la fuente principal deja de hacerlo." },
  "104": { "domain": "Ingest", "explanation": "IntegrationHub ETL muestra mappings de campos que transforman datos externos antes de insertarlos." },
  "105": { "domain": "Ingest", "explanation": "IntegrationHub ETL integra datos usando IRE para asegurar calidad y evitar duplicados." },
  "106": { "domain": "Ingest", "explanation": "Service Graph Connectors son el método recomendado para integraciones rápidas y estandarizadas." },
  "107": { "domain": "Ingest", "explanation": "Las customizaciones en conectores generan skipped changes durante upgrades para proteger cambios locales." },
  "108": { "domain": "Ingest", "explanation": "CMDBTransformUtil asegura que los datos importados pasen por el IRE evitando duplicados." },
  "109": { "domain": "Ingest", "explanation": "Las categorías Cloud y Observability agrupan integraciones modernas como AWS o herramientas de monitorización." },
  "110": { "domain": "Configuration", "explanation": "Las reglas más específicas prevalecen sobre generales en reconciliación, aplicándose primero a subclases." },

  "111": { "domain": "Ingest", "explanation": "Service Graph Connectors reducen deuda técnica al ser integraciones estándar mantenidas por ServiceNow." },
  "112": { "domain": "Ingest", "explanation": "Discovery y Service Mapping crean relaciones automáticamente identificando dependencias técnicas." },
  "113": { "domain": "Configuration", "explanation": "Las reglas dinámicas requieren multisource CMDB o CMDB 360 para funcionar correctamente." },
  "114": { "domain": "Ingest", "explanation": "El conector SCCM es el método recomendado para integrar dispositivos Windows rápidamente." },
  "115": { "domain": "Ingest", "explanation": "Las customizaciones en Service Graph no están soportadas y deben mantenerse manualmente." },
  "116": { "domain": "Ingest", "explanation": "Los conectores se gestionan desde CMDB Workspace tras instalar el plugin correspondiente." },
  "117": { "domain": "Govern", "explanation": "Los scheduled jobs automatizan eliminación definitiva de CIs retirados." },
  "118": { "domain": "Insight", "explanation": "Los playbooks guían resolución de problemas pero no ejecutan correcciones automáticamente." },
  "119": { "domain": "Insight", "explanation": "Los playbooks incluyen análisis y descripción del problema antes de actuar." },
  "120": { "domain": "Insight", "explanation": "El valor de los playbooks es entender impacto y sugerir acciones correctivas." },

  "121": { "domain": "Govern", "explanation": "Data Manager permite eliminar registros obsoletos mediante políticas automatizadas." },
  "122": { "domain": "Govern", "explanation": "El campo last_discovery sirve para medir staleness y determinar vigencia de CIs." },
  "123": { "domain": "Govern", "explanation": "La Certification valida que los datos del CI son correctos y actualizados." },
  "124": { "domain": "Configuration", "explanation": "La reconciliación prioriza fuentes fiables para evitar inconsistencias de datos." },
  "125": { "domain": "Configuration", "explanation": "El IRE consolida datos de múltiples fuentes creando una única versión confiable del CI." },
  "126": { "domain": "Configuration", "explanation": "Las reglas de identificación determinan qué atributos hacen único un CI." },
  "127": { "domain": "Configuration", "explanation": "La consistencia en atributos clave evita creación de duplicados entre fuentes." },
  "128": { "domain": "Configuration", "explanation": "CI Class Manager centraliza jerarquía, atributos y relaciones del modelo CMDB." },
  "129": { "domain": "Ingest", "explanation": "Service Graph Connectors simplifican la ingestión estandarizada de datos." },
  "130": { "domain": "Configuration", "explanation": "Las reglas de prioridad determinan qué fuente prevalece en conflictos." },

  "131": { "domain": "Insight", "explanation": "Las relaciones entre CIs permiten analizar dependencias y evaluar impacto operativo." },
  "132": { "domain": "Govern", "explanation": "El Health Dashboard monitoriza calidad y detecta problemas en CMDB." },
  "133": { "domain": "Govern", "explanation": "Las políticas de ciclo de vida controlan creación, uso y retirada de CIs." },
  "134": { "domain": "Govern", "explanation": "La deduplicación combina identificación automática y acciones manuales." },
  "135": { "domain": "Configuration", "explanation": "Las reglas de reconciliación controlan qué fuente actualiza cada atributo." },
  "136": { "domain": "Insight", "explanation": "Los playbooks ayudan a resolver problemas mediante análisis estructurado." },
  "137": { "domain": "Configuration", "explanation": "Una correcta clasificación mejora reporting y análisis en CMDB." },
  "138": { "domain": "Ingest", "explanation": "Las integraciones automatizadas reducen errores y mejoran consistencia de datos." },
  "139": { "domain": "Insight", "explanation": "Las queries permiten agrupar y analizar CIs dinámicamente." },
  "140": { "domain": "Insight", "explanation": "CMDB Workspace centraliza herramientas y visualización operativa." },

  "141": { "domain": "Govern", "explanation": "Archive policies permiten retirar datos antiguos manteniendo historial." },
  "142": { "domain": "Govern", "explanation": "Los dashboards permiten identificar problemas rápidamente." },
  "143": { "domain": "Govern", "explanation": "La gobernanza asegura mantenimiento continuo del CMDB." },
  "144": { "domain": "Insight", "explanation": "El modelado de servicios conecta negocio con tecnología." },
  "145": { "domain": "Insight", "explanation": "Las relaciones permiten evaluar impacto en el negocio." },
  "146": { "domain": "Ingest", "explanation": "La automatización reduce esfuerzo manual y mejora precisión." },
  "147": { "domain": "Govern", "explanation": "Los atributos obligatorios aseguran completitud mínima de datos." },
  "148": { "domain": "Configuration", "explanation": "Los estándares reducen deuda técnica y mejoran mantenimiento." },
  "149": { "domain": "Govern", "explanation": "La gestión de roles asegura responsabilidades claras sobre datos." },
  "150": { "domain": "Govern", "explanation": "La mejora continua se basa en métricas de calidad del CMDB." },

  "151": { "domain": "Insight", "explanation": "El CMDB mejora procesos ITSM proporcionando visibilidad del impacto entre CIs." },
  "152": { "domain": "Ingest", "explanation": "La integración consistente evita duplicados mediante uso adecuado del IRE." },
  "153": { "domain": "Govern", "explanation": "Las políticas de calidad detectan errores y mantienen confiabilidad." },
  "154": { "domain": "Insight", "explanation": "El modelado de servicios facilita análisis de impacto y continuidad." },
  "155": { "domain": "Configuration", "explanation": "Las reglas IRE consolidan datos creando una única fuente confiable." },
  "156": { "domain": "Insight", "explanation": "Los dashboards permiten monitorizar calidad y tomar decisiones." },
  "157": { "domain": "Configuration", "explanation": "La estandarización mejora mantenimiento y reutilización del modelo." },
  "158": { "domain": "Ingest", "explanation": "Las integraciones automatizadas aseguran coherencia en datos." },
  "159": { "domain": "Insight", "explanation": "Las relaciones permiten entender impacto entre componentes." },
  "160": { "domain": "Govern", "explanation": "El lifecycle controla evolución de los CIs." },

  "161": { "domain": "Insight", "explanation": "La visibilidad completa mejora decisiones operativas." },
  "162": { "domain": "Govern", "explanation": "La validación asegura precisión de datos." },
  "163": { "domain": "Govern", "explanation": "Las herramientas de deduplicación consolidan registros duplicados." },
  "164": { "domain": "Govern", "explanation": "Las políticas automatizan mantenimiento del CMDB." },
  "165": { "domain": "CSDM", "explanation": "CSDM alinea negocio y tecnología en la CMDB." },
  "166": { "domain": "Govern", "explanation": "Los roles aseguran responsabilidad sobre datos." },
  "167": { "domain": "Insight", "explanation": "Las métricas permiten mejora continua del CMDB." },
  "168": { "domain": "Configuration", "explanation": "Las reglas de reconciliación controlan conflictos multisource." },
  "169": { "domain": "Insight", "explanation": "Un CMDB correcto permite evaluar impacto rápidamente." },
  "170": { "domain": "Configuration", "explanation": "Los atributos definen información relevante del CI." },

  "171": { "domain": "Ingest", "explanation": "La automatización reduce errores humanos en ingestion de datos." },
  "172": { "domain": "Insight", "explanation": "Las relaciones estructuradas facilitan análisis de dependencias." },
  "173": { "domain": "Govern", "explanation": "Las políticas de retención eliminan datos innecesarios." },
  "174": { "domain": "Configuration", "explanation": "Una buena estructura mejora navegación y gestión CMDB." },
  "175": { "domain": "Configuration", "explanation": "La identificación correcta evita duplicados de CIs." },
  "176": { "domain": "Govern", "explanation": "Las revisiones periódicas aseguran vigencia de datos." },
  "177": { "domain": "Insight", "explanation": "Las visualizaciones ayudan a entender relaciones entre CIs." },
  "178": { "domain": "Ingest", "explanation": "La integración adecuada mejora calidad global del CMDB." },
  "179": { "domain": "CSDM", "explanation": "La organización de servicios mejora entrega de valor al negocio." },
  "180": { "domain": "Insight", "explanation": "Las métricas permiten priorizar acciones correctivas." },

  "181": { "domain": "Configuration", "explanation": "Los estándares aseguran consistencia entre procesos y equipos." },
  "182": { "domain": "Govern", "explanation": "La gestión centralizada facilita control y gobernanza." },
  "183": { "domain": "Insight", "explanation": "El análisis de relaciones permite comprender impactos en cascada." },
  "184": { "domain": "Govern", "explanation": "El mantenimiento continuo evita degradación de calidad." },
  "185": { "domain": "Configuration", "explanation": "El modelo CMDB bien definido mejora eficiencia operativa." },
  "186": { "domain": "CSDM", "explanation": "Information Objects representan datos de negocio asociados a aplicaciones." },
  "187": { "domain": "CSDM", "explanation": "Technology Management Offerings automatizan atributos operativos en CSDM." },
  "188": { "domain": "CSDM", "explanation": "Data Foundations Dashboard ayuda a identificar gaps de modelado CSDM." },
  "189": { "domain": "CSDM", "explanation": "Los playbooks CSDM mejoran relaciones entre application services y negocio." },
  "190": { "domain": "CSDM", "explanation": "Application Service y Service Offering conectan operaciones ITSM con servicios." },

  "191": { "domain": "CSDM", "explanation": "Service Portfolio pertenece a Service Consumption en CSDM." },
  "192": { "domain": "Insight", "explanation": "El motor IRE (Identification Reconciliation Engine) utiliza varias system properties para activar y ajustar el funcionamiento de CMDB 360/Multisource CMDB. La propiedad principal que habilita toda la funcionalidad es glide.identification_engine.multisource_enabled, mientras que otras propiedades complementarias controlan qué tipos de CI pueden registrar datos multisource y cuántos registros se pueden consultar simultáneamente." },
  "193": { "domain": "Configuration", "explanation": "" },
  "194": { "domain": "Govern", "explanation": "Como la pregunta pide confirmar que un atributo concreto (la Location) tiene el valor correcto, no simplemente que el CI exista, la policy correcta es Certification y no Attestation." }
}
